src/Entity/Item.php
<?php

namespace App\Entity;

use App\Repository\ItemRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ItemRepository::class)]
class Item
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $login_id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?int $platform_id = null;

    #[ORM\Column(length: 255)]
    private ?string $name_curl = null;

    #[ORM\Column(length: 255)]
    private ?string $wiki_url = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageUrl = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLoginId(): ?int
    {
        return $this->login_id;
    }

    public function setLoginId(int $login_id): static
    {
        $this->login_id = $login_id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getPlatformId(): ?int
    {
        return $this->platform_id;
    }

    public function setPlatformId(int $platform_id): static
    {
        $this->platform_id = $platform_id;

        return $this;
    }

    public function getNameCurl(): ?string
    {
        return $this->name_curl;
    }

    public function setNameCurl(string $name_curl): static
    {
        $this->name_curl = $name_curl;

        return $this;
    }

    public function getWikiUrl(): ?string
    {
        return $this->wiki_url;
    }

    public function setWikiUrl(string $wiki_url): static
    {
        $this->wiki_url = $wiki_url;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->imageUrl;
    }

    public function setImageUrl(?string $imageUrl): static
    {
        $this->imageUrl = $imageUrl;

        return $this;
    }
}

src/Entity/Watchlist.php
<?php

namespace App\Entity;

use App\Repository\WatchlistRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: WatchlistRepository::class)]
#[ORM\Table(name: 'items_on_watchlist')]
class Watchlist
{
    #[ORM\Id]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?int $login_id = null;

    #[ORM\Column(length: 255)]
    private ?string $platform_name = null;

    #[ORM\Column(length: 255)]
    private ?string $wiki_url = null;

    #[ORM\Column(length: 255)]
    private ?string $image_url = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getLoginId(): ?int
    {
        return $this->login_id;
    }

    public function getPlatformName(): ?string
    {
        return $this->platform_name;
    }

    public function getWikiUrl(): ?string
    {
        return $this->wiki_url;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }
}

src/Controller/ItemController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use App\Repository\WatchlistRepository;
use App\Service\Item\ItemService;
use App\UniqueNameInterface\JsonResponseInterface;
use App\Service\WarframeMarket\MarketService;
use App\UniqueNameInterface\ItemInterface;
use App\UniqueNameInterface\WarframeApiInterface;

#[Route('/item')]
class ItemController extends AbstractController
{
    #[Route('/watched', name: 'item_watched')]
    public function watched (
        WatchlistRepository $watchlistRepository,
        UserInterface       $login
    ): Response
    {
        $itemsWatched = $watchlistRepository->findBy(['login_id' => $login->getId()]);

        return $this->render('item/watched.html.twig', [
            'items_watched' => $itemsWatched,
        ]);
    }

    #[Route('/add', name: 'item_add')]
    public function add (
        Request         $request,
        ItemService     $itemService
    ): JsonResponse|RedirectResponse
    {
        $loginId = $this->getUser()->getId();
        $data = $request->request->all();
        $statusCode = 200;
        $validator = $itemService->validateData($data);

        if ($itemService->checkIfAlreadyWatched($loginId, (int)$data[ItemInterface::FORM_PLATFORMID], $data[ItemInterface::ENTITY_NAME])) {

            return $this->redirectToRoute('item_edit', $data);
        }
        elseif (!$itemService->itemExistsInApi($data[ItemInterface::FORM_NAME])) {
            $msg = [
                JsonResponseInterface::MESSAGE => 'Something wrong with name of searched item'
            ];
            $statusCode = 400;
        }
        elseif (0 !== count($validator)) {
            $msg = $validator[0]; // show first error only
            $statusCode = 400;
        }
        else {
            $itemService->addItemToWatchlist($data, $loginId);
            $msg = [
                JsonResponseInterface::MESSAGE => 'Successfully added item to watch-list'
            ];
        }

        return new JsonResponse($msg, $statusCode);
    }

    #[Route('/search_market/{name}', name: 'item_search_market', methods: ['GET'])]
    public function searchMarket (
        string          $name,
        MarketService   $marketService,
        ItemService     $itemService,
    ): Response {
        $items = $marketService->getWarframeMarketData($name);
        $wikiUrl = $itemService->getImageUrl(
            strtolower(preg_replace('/\s+/', '_', $name)),
            0
        );
        $itemData = $marketService->getItemData($name);
        // it's awfully nested array, charming api huh?
        $itemDescription = $itemData[WarframeApiInterface::INCLUDE_ITEM]
            [WarframeApiInterface::INCLUDE_ITEM_ITEMSINSET]
            [WarframeApiInterface::INCLUDE_ITEM_ITEMSINSET_FIRSTKEY]
            [WarframeApiInterface::INCLUDE_ITEM_ITEMSINSET_FIRSTKEY_LANG_EN]
            [WarframeApiInterface::INCLUDE_ITEM_ITEMSINSET_FIRSTKEY_LANG_EN_DESCRIPTION]
        ;

        return $this->render('item/searchMarket.html.twig', [
            'items'             => array_slice($items, 0, 13),
            'item_name'         => $name,
            'wiki_url'          => $wikiUrl,
            'item_description'  => $itemDescription
        ]);
    }

    #[Route('/delete', name: 'item_delete', methods: 'DELETE')]
    public function delete (
        Request     $request,
        ItemService $itemService
    ): JsonResponse {
        $data = $request->request->all();
        $statusCode = 200;
        $itemService->deleteItem((int)$data[ItemInterface::FORM_ID]);
        $msg = [
            JsonResponseInterface::MESSAGE => 'Successfully deleted item from watch-list'
        ];

        return new JsonResponse($msg, $statusCode);
    }

    #[Route('/edit', name: 'item_edit')]
    public function edit (
        Request     $request,
        ItemService $itemService
    ): JsonResponse {
        $data = $request->query->all();
        $statusCode = 200;
        $validator = $itemService->validateData($data);
        if (0 !== count($validator)) {
            $msg = $validator[0]; // show first error only
            $statusCode = 400;
        } else {
            $itemService->editItem($this->getUser(), $data);
            $msg = [
                JsonResponseInterface::MESSAGE => 'You have edited price of: ' . $data[ItemInterface::FORM_NAME]
            ];
        }
        return new JsonResponse($msg, $statusCode);
    }
}

templates/item/followNew.html.twig
<div class="modal">
    <div id="background">
        <div class="row">
            <div class="col-6 offset-3 container wrapper" id="follow">
                <div class="row">
                    <div class="col-12">
                        <div class="col-12 modalBody" id="addNew">
                            <div class="row">
                                <div class="col-12 title">
                                    <div class="col-11"><p>Add item to watch</p></div>
                                    <div class="col-1 closeButton smallExit" data-title="Close form"><i class="icon icon-cancel"></i></div>
                                </div>
                            </div>
                            <div class="row col-12" id="content">
                                <div class="col-12">
                                    {# it's called as ajax request #}
                                    <form action="{{ url('item_add') }}" method="post" id="formFollow" class="col-12" autocomplete="off">
{#TODO: ADD CSRF#}
                                        <div class="form-group col-12">
                                            <span><label for="itemNameinput">Search for item part</label></span><br>
                                            <input list="itemsList" type="text" class="col-12 itemNameinput" id="itemNameinput" name="name" placeholder="Search...">
                                        </div>
                                        <div class="form-group col-12">
                                            <span><label for="itemPrice">Price</label></span><br>
                                            <input type="number" name="price" placeholder="Price for item" id="itemPrice">
                                        </div>
                                        <div class="form-group col-12">
                                            <span><label for="platformChangeUser">Platform</label></span><br>
                                            <select class="platform" id="platformChangeUser" name="platformId">
                                                <option value="1" {% if app.user.platformid is same as 1 %} selected {% endif %}>PC</option>
                                                <option value="2" {% if app.user.platformid is same as 2 %} selected {% endif %}>XBOX</option>
                                                <option value="3" {% if app.user.platformid is same as 3 %} selected {% endif %}>PS</option>
                                                <option value="4" {% if app.user.platformid is same as 4 %} selected {% endif %}>Switch</option>
                                            </select>
                                        </div>
                                        <div class="col-12" id="buttons">
                                            <div class="col-4">
                                                <button class="btn btn-outline-secondary closeButton" data-title="Close uploader">Cancel</button>
                                            </div>
                                            <div class="col-2 offset-6">
                                                <button type="submit" class="btn btn-outline-primary submit" data-title="Rename file">Create</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>  
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/item/searchMarket.html.twig
{% extends('layouts/app.html.twig') %}

{% block content %}

    {% if items|length > 0 %}
            <div class="col-10 offset-1 searchedItems">
                <div class="col-9">
                    <div class="col-12 itemRow">
                        <div class="col-4">
                            <span>Username</span>
                        </div>
                        <div class="status col-3">
                            <span>In-game status</span>
                        </div>
                        <div class="price col-2">
                            <span>Price</span>
                        </div>
                    </div>
                    {% for item in items %}
                        <div class="col-12 itemRow">
                            <div class="dmSellerInput col-9">
                                <input class="col-12" type="text" value="/w {{ item.user.ingame_name }} Hi {{ item.user.ingame_name }}! I want to buy [{{ item_name }}] for {{ item.platinum }} platinum. Is it still available?">
                            </div>
                            <div class="username col-4">
                                <span>{{ item.user.ingame_name }}</span>
                            </div>
                            <div class="status col-3">
                                <span>{{ item.user.status }}</span>
                            </div>
                            <div class="price col-2">
                                <span>{{ item.platinum }}</span>
                            </div>
                            <div class="action col-3">
                                <button type="button" class="tooltipButton btn btn-outline-primary copyTextToClipboard" data-tooltip-placement="right" data-title="Copy to clipboard">Buy <i class="icon icon-tag"></i></button>
                            </div>

                        </div>
                    {% endfor %}
                </div>
                <div class="col-3" id="itemDescription">
                    <div class="col-12 title">{{ item_name }}</div>
                    <div class="col-12 picture">
                        <img src="https://raw.githubusercontent.com/wfcd/warframe-items/master/data/img/{{ wiki_url }}" alt="{{ item_name }}">
                    </div>
                    <div class="col-12 description">
                        {{ item_description }}
                    </div>
                </div>
            </div>

    {% else %}
        <div class="col-6 offset-3 text-center">
            <p><h2>Apparently there are no active offers of {{ item_name }}</h2></p>
        </div>
    {% endif %}

{% endblock %}

templates/item/watched.html.twig
{% extends('layouts/app.html.twig') %}

{% block content %}

    <div id="watched" class="col-12">
        {% if items_watched|length > 0 %}
            {% for item in items_watched %}
                <div class="orderPanel">
                    <div class="col-7 description">
                        <div class="col-12"><p class="itemname"><a href="https://warframe.fandom.com/wiki/{{ item.wikiUrl }}" class="tooltipButton" data-tooltip-placement="top" data-title="Go to Warframe wiki">{{item.name}}</a></p></div>
                        <div class="col-12"><p class="price">Price: {{item.price}} platinum</p></div>
                        <div class="col-12"><p class="platform">Platform: {{item.platformName}}</p></div>
                        <div class="col-12 orderMenagment">
                            <div><span class="col-3 editOrder edit tooltipButton" data-price='{{item.price}}' data-item='{{item.name}}' data-platform='{{item.platformName}}' data-tooltip-placement="bottom" data-title="Edit price of order"><i class="icon icon-pencil"></i></span></div>
                            <div><span class="col-3 offset-4 editOrder delete deleteWatched tooltipButton" data-id='{{item.id}}' data-tooltip-placement="bottom" data-title="Delete from watchlist"><i class="icon icon-cancel"></i></span></div>
                        </div>
                    </div>
                    <div class="col-5 picture">
                        <img src="https://raw.githubusercontent.com/wfcd/warframe-items/master/data/img/{{ item.imageUrl }}" alt="{{ item.name }}">
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-6 offset-3 text-center">
                <p><h2>Add items to watch-list to start!</h2></p>
            </div>
        {% endif %}
    </div>

{% endblock %}